name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn clean package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.tgz
